spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      file-size-threshold : 1MB
      location : C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8090


