spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create


upload-path: "C:\\Temp"

cloud:
  aws:
    credentials:
      accessKey: AKIAWPZT6RJRIDLXOFNX       # AWS IAM AccessKey 적기
      secretKey: QMWmPDAlS9SHSXKYTuJUt3PFkobkyvtNCYk7Z6/l   # AWS IAM SecretKey 적기
    s3:
      bucket: gurumi-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
